language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == 2 ]]; then pip install unittest2; fi
    - pip install -r requirements.txt
    - python setup.py install
script:
    - nosetests

